name: lists
version: 0.0.2
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Collection of the lists (BitList, FilledList, FixedList, RangeList, StepList).
homepage: https://github.com/mezoni/lists
dev_dependencies:
  unittest: any
